version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  push-image:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: 
          name: Update image tag
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            sed -i.bak -E "s/image:\ docker\.io\/bjimerson\/command-runner([:][0-9]\.[0-9]+\.[0-9]+)?/image:\ docker\.io\/bjimerson\/command-runner:$TAG/" deploy/deployment.yaml
      - add_ssh_keys:
          fingerprints:
            - "1e:13:63:ac:4b:db:41:64:20:3a:48:cc:87:18:61:e0"          
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - setup_remote_docker:
          name: Setup Docker environment
          docker_layer_caching: false
      - run: 
          name: Create and push image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t bjimerson/kickstarter:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push bjimerson/kickstarter:$TAG
      - run:
          name: Push image tag
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            git config user.email "bjimerson@gmail.com"
            git config user.name "CircleCI Job"
            git checkout main
            git commit --allow-empty -am "Update image tag from CircleCI to $TAG [skip ci]"
            git push origin main
workflows:
  release:
    jobs:
      - build-and-test
      - push-image:
          requires:
            - build-and-test
          context: jimerson-dockerhub-credentials
