---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstarter
  namespace: kickstarter
  labels:
    app: kickstarter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickstarter
  template:
    metadata:
      labels:
        app: kickstarter
    spec:
      containers:
      - name: kickstarter
        image: harbor.pintobean.xyz/kickstarter/kickstarter:0.1.18
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
