---
apiVersion: v1
kind: Service
metadata:
  name: kickstarter
  namespace: kickstarter
  labels:
    service: kickstarter
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kickstarter